export const companiesData = [
  {
    id: 1,
    name: "Torphy - Klein",
    industry: "Брендинг",
    email: "contact@torphy-klein.com",
    phone: "+1 (231) 577 983",
    address: { city: "Dallas", street: "8906 Lelia Parks" },
    employees: 120,
    revenue: 150,
    status: "активный",
  },
  {
    id: 2,
    name: "GreenTech LLC",
    industry: "Возобновляемая энергия",
    email: "info@greentech.com",
    phone: "+ 1 (987) 654 3210",
    address: { city: "Austin", street: "1234 Elm Street" },
    employees: 85,
    revenue: 300,
    status: "активный",
  },
  {
    id: 3,
    name: "TechSolutions",
    industry: "Разработка ПО",
    email: "support@techsolutions.com",
    phone: "+1 (555) 123 456",
    address: { city: "New York", street: "56 Broadway Ave" },
    employees: 300,
    revenue: 240,
    status: "активный",
  },
  {
    id: 4,
    name: "CreativeLabs",
    industry: "Дизайн и инновации",
    email: "hello@creativelabs.com",
    phone: "+1 (444) 555 666",
    address: { city: "Los Angeles", street: "789 Sunset Blvd" },
    employees: 95,
    revenue: 350,
    status: "активный",
  },
  {
    id: 5,
    name: "FinCorp",
    industry: "Финансы",
    email: "contact@fincorp.com",
    phone: "+2 (222) 333 444",
    address: { city: "Chicago", street: "321 Oak Street" },
    employees: 150,
    revenue: 200,
    status: "активный",
  },
  {
    id: 6,
    name: "MediaHouse",
    industry: "СМИ и развлечения",
    email: "info@mediahouse.com",
    phone: "+2 (111) 222 333",
    address: { city: "Miami", street: "654 Ocean Drive" },
    employees: 60,
    revenue: 200,
    status: "активный",
  },
  {
    id: 7,
    name: "Gerlinf",
    industry: "СМИ",
    email: "info@ger.com",
    phone: "+1 (345) 222 333",
    address: { city: "Miami", street: "658 Drive" },
    employees: 340,
    revenue: 1200,
    status: "активный",
  },
  {
    id: 8,
    name: "Fortin",
    industry: "развлечения",
    email: "info@tin.com",
    phone: "+1 (349) 222 333",
    address: { city: "Miami", street: "659 Drive" },
    employees: 240,
    revenue: 1000,
    status: "активный",
  },
  {
    id: 9,
    name: "Lauren",
    industry: "Дизайн",
    email: "info@lauren.com",
    phone: "+1 (334) 222 333",
    address: { city: "Miami", street: "653 Mort" },
    employees: 140,
    revenue: 800,
    status: "активный",
  },
  {
    id: 10,
    name: "Qwerni",
    industry: "Брендинг",
    email: "info@qwer.com",
    phone: "+4 (734) 222 333",
    address: { city: "Ohio", street: "653 Nory" },
    employees: 940,
    revenue: 130,
    status: "активный",
  },
  {
    id: 11,
    name: "Morlen",
    industry: "Брендинг",
    email: "info@mor.com",
    phone: "+1 (340) 222 333",
    address: { city: "Virginia", street: "278 Gert" },
    employees: 670,
    revenue: 1100,
    status: "активный",
  },
  {
    id: 12,
    name: "Uner",
    industry: "Возобновляемая энергия",
    email: "info@uner.com",
    phone: "+1 (349) 222 333",
    address: { city: "California", street: "654 Wero" },
    employees: 200,
    revenue: 870,
    status: "активный",
  },
];
