export const dataUsersPagination = [
  {
    id: 1,
    firstName: "Дмитрий",
    lastName: "Новиков",
    age: 48,
    visits: 54,
    progress: 7,
  },
  {
    id: 2,
    firstName: "Андрей",
    lastName: "Ковалев",
    age: 30,
    visits: 50,
    progress: 10,
  },
  {
    id: 3,
    firstName: "Владимир",
    lastName: "Иванов",
    age: 32,
    visits: 5,
    progress: 15,
  },
  {
    id: 4,
    firstName: "Сергей",
    lastName: "Дроздов",
    age: 47,
    visits: 9,
    progress: 7,
  },
  {
    id: 5,
    firstName: "Федор",
    lastName: "Быстров",
    age: 30,
    visits: 5,
    progress: 12,
  },
  {
    id: 6,
    firstName: "Николай",
    lastName: "Лебедев",
    age: 20,
    visits: 28,
    progress: 27,
  },
  {
    id: 7,
    firstName: "Артур",
    lastName: "Минько",
    age: 29,
    visits: 45,
    progress: 60,
  },
  {
    id: 8,
    firstName: "Георгий",
    lastName: "Гончаров",
    age: 47,
    visits: 2,
    progress: 36,
  },
  {
    id: 9,
    firstName: "Егор",
    lastName: "Аркадьев",
    age: 40,
    visits: 5,
    progress: 46,
  },
  {
    id: 10,
    firstName: "Станислав",
    lastName: "Иванов",
    age: 56,
    visits: 23,
    progress: 80,
  },
  {
    id: 11,
    firstName: "Петр",
    lastName: "Кузнецов",
    age: 23,
    visits: 4,
    progress: 60,
  },
  {
    id: 12,
    firstName: "Антон",
    lastName: "Лазарев",
    age: 30,
    visits: 67,
    progress: 39,
  },
  {
    id: 13,
    firstName: "Владислав",
    lastName: "Карпов",
    age: 47,
    visits: 28,
    progress: 96,
  },
  {
    id: 14,
    firstName: "Валерий",
    lastName: "Медведев",
    age: 35,
    visits: 24,
    progress: 76,
  },
  {
    id: 15,
    firstName: "Евгений",
    lastName: "Данилов",
    age: 28,
    visits: 39,
    progress: 80,
  },
  {
    id: 16,
    firstName: "Александр",
    lastName: "Смирнов",
    age: 43,
    visits: 38,
    progress: 70,
  },
  {
    id: 17,
    firstName: "Михаил",
    lastName: "Иванов",
    age: 49,
    visits: 12,
    progress: 40,
  },
  {
    id: 18,
    firstName: "Максим",
    lastName: "Кузнецов",
    age: 23,
    visits: 34,
    progress: 10,
  },
  {
    id: 19,
    firstName: "Артем",
    lastName: "Попов",
    age: 20,
    visits: 30,
    progress: 54,
  },
  {
    id: 20,
    firstName: "Иван",
    lastName: "Васильев",
    age: 27,
    visits: 32,
    progress: 30,
  },
  {
    id: 21,
    firstName: "Алексей",
    lastName: "Иванов",
    age: 19,
    visits: 3,
    progress: 50,
  },
  {
    id: 22,
    firstName: "Артём",
    lastName: "Смирнов",
    age: 22,
    visits: 5,
    progress: 24,
  },
  {
    id: 23,
    firstName: "Вадим",
    lastName: "Кузнецов",
    age: 34,
    visits: 20,
    progress: 23,
  },
  {
    id: 24,
    firstName: "Владимир",
    lastName: "Попов",
    age: 22,
    visits: 17,
    progress: 21,
  },
  {
    id: 25,
    firstName: "Валентин",
    lastName: "Васильев",
    age: 23,
    visits: 7,
    progress: 18,
  },
  {
    id: 26,
    firstName: "Данил",
    lastName: "Петров",
    age: 45,
    visits: 56,
    progress: 27,
  },
  {
    id: 27,
    firstName: "Денис",
    lastName: "Соколов",
    age: 42,
    visits: 9,
    progress: 87,
  },
  {
    id: 28,
    firstName: "Дмитрий",
    lastName: "Михайлов",
    age: 26,
    visits: 10,
    progress: 56,
  },
  {
    id: 29,
    firstName: "Егор",
    lastName: "Новиков",
    age: 29,
    visits: 24,
    progress: 39,
  },
  {
    id: 30,
    firstName: "Кирилл",
    lastName: "Фёдоров",
    age: 25,
    visits: 7,
    progress: 37,
  },
  {
    id: 31,
    firstName: "Леонид",
    lastName: "Морозов",
    age: 25,
    visits: 9,
    progress: 16,
  },
  {
    id: 32,
    firstName: "Максим",
    lastName: "Волков",
    age: 23,
    visits: 37,
    progress: 49,
  },
  {
    id: 33,
    firstName: "Матвей",
    lastName: "Алексеев",
    age: 32,
    visits: 89,
    progress: 25,
  },
  {
    id: 34,
    firstName: "Никита",
    lastName: "Лебедев",
    age: 19,
    visits: 26,
    progress: 29,
  },
  {
    id: 35,
    firstName: "Олег",
    lastName: "Семёнов",
    age: 29,
    visits: 37,
    progress: 89,
  },
  {
    id: 36,
    firstName: "Павел",
    lastName: "Егоров",
    age: 24,
    visits: 23,
    progress: 75,
  },
  {
    id: 37,
    firstName: "Пётр",
    lastName: "Павлов",
    age: 49,
    visits: 67,
    progress: 80,
  },
  {
    id: 38,
    firstName: "Роман",
    lastName: "Козлов",
    age: 28,
    visits: 6,
    progress: 29,
  },
  {
    id: 39,
    firstName: "Денис",
    lastName: "Фёдоров",
    age: 25,
    visits: 19,
    progress: 28,
  },
  {
    id: 40,
    firstName: "Сергей",
    lastName: "Ковалев",
    age: 29,
    visits: 7,
    progress: 24,
  },
  {
    id: 41,
    firstName: "Константин",
    lastName: "Герасименко",
    age: 39,
    visits: 26,
    progress: 69,
  },
  {
    id: 42,
    firstName: "Сергей",
    lastName: "Иваньков",
    age: 30,
    visits: 76,
    progress: 47,
  },
  {
    id: 43,
    firstName: "Николай",
    lastName: "Егоров",
    age: 30,
    visits: 9,
    progress: 67,
  },
  {
    id: 44,
    firstName: "Станислав",
    lastName: "Иванов",
    age: 19,
    visits: 3,
    progress: 29,
  },
  {
    id: 45,
    firstName: "Герман",
    lastName: "Ивановский",
    age: 31,
    visits: 87,
    progress: 90,
  },
  {
    id: 46,
    firstName: "Андрей",
    lastName: "Маркин",
    age: 45,
    visits: 29,
    progress: 40,
  },
  {
    id: 47,
    firstName: "Дмитрий",
    lastName: "Волков",
    age: 21,
    visits: 17,
    progress: 23,
  },
  {
    id: 48,
    firstName: "Егор",
    lastName: "Громов",
    age: 24,
    visits: 39,
    progress: 30,
  },
  {
    id: 49,
    firstName: "Станислав",
    lastName: "Иванов",
    age: 20,
    visits: 19,
    progress: 23,
  },
  {
    id: 50,
    firstName: "Иван",
    lastName: "Афанасьев",
    age: 38,
    visits: 30,
    progress: 65,
  },
  {
    id: 51,
    firstName: "Александр",
    lastName: "Громов",
    age: 35,
    visits: 20,
    progress: 30,
  },
  {
    id: 52,
    firstName: "Никита",
    lastName: "Лебедев",
    age: 50,
    visits: 30,
    progress: 80,
  },
  {
    id: 53,
    firstName: "Дмитрий",
    lastName: "Михайлов",
    age: 41,
    visits: 19,
    progress: 23,
  },
  {
    id: 54,
    firstName: "Алена",
    lastName: "Иванова",
    age: 27,
    visits: 19,
    progress: 93,
  },
  {
    id: 55,
    firstName: "Анастасия",
    lastName: "Смирнова",
    age: 20,
    visits: 16,
    progress: 29,
  },
  {
    id: 56,
    firstName: "Вероника",
    lastName: "Попова",
    age: 19,
    visits: 3,
    progress: 65,
  },
  {
    id: 57,
    firstName: "Виктория",
    lastName: "Васильева",
    age: 45,
    visits: 83,
    progress: 96,
  },
  {
    id: 58,
    firstName: "Екатерина",
    lastName: "Петрова",
    age: 19,
    visits: 32,
    progress: 54,
  },
  {
    id: 59,
    firstName: "Елена",
    lastName: "Соколова",
    age: 23,
    visits: 45,
    progress: 50,
  },
  {
    id: 60,
    firstName: "Ирина",
    lastName: "Михайлова",
    age: 23,
    visits: 6,
    progress: 85,
  },
];
