export const dataUsers = [
  {
    id: 1,
    firstName: "Дмитрий",
    lastName: "Новиков",
    age: 48,
    visits: 54,
    progress: 7,
  },
  {
    id: 2,
    firstName: "Андрей",
    lastName: "Ковалев",
    age: 30,
    visits: 50,
    progress: 10,
  },
  {
    id: 3,
    firstName: "Владимир",
    lastName: "Иванов",
    age: 32,
    visits: 5,
    progress: 15,
  },
  {
    id: 4,
    firstName: "Сергей",
    lastName: "Дроздов",
    age: 47,
    visits: 9,
    progress: 7,
  },
  {
    id: 5,
    firstName: "Федор",
    lastName: "Быстров",
    age: 30,
    visits: 5,
    progress: 12,
  },
  {
    id: 6,
    firstName: "Николай",
    lastName: "Лебедев",
    age: 20,
    visits: 28,
    progress: 27,
  },
  {
    id: 7,
    firstName: "Артур",
    lastName: "Минько",
    age: 29,
    visits: 45,
    progress: 60,
  },
  {
    id: 8,
    firstName: "Георгий",
    lastName: "Гончаров",
    age: 47,
    visits: 2,
    progress: 36,
  },
  {
    id: 9,
    firstName: "Егор",
    lastName: "Аркадьев",
    age: 40,
    visits: 5,
    progress: 46,
  },
  {
    id: 10,
    firstName: "Станислав",
    lastName: "Иванов",
    age: 56,
    visits: 23,
    progress: 80,
  },
  {
    id: 11,
    firstName: "Петр",
    lastName: "Кузнецов",
    age: 23,
    visits: 4,
    progress: 60,
  },
  {
    id: 12,
    firstName: "Антон",
    lastName: "Лазарев",
    age: 30,
    visits: 67,
    progress: 39,
  },
  {
    id: 13,
    firstName: "Владислав",
    lastName: "Карпов",
    age: 47,
    visits: 28,
    progress: 96,
  },
  {
    id: 14,
    firstName: "Валерий",
    lastName: "Медведев",
    age: 35,
    visits: 24,
    progress: 76,
  },
  {
    id: 15,
    firstName: "Евгений",
    lastName: "Данилов",
    age: 28,
    visits: 39,
    progress: 80,
  },
];
